pre<-read.table('./data/ODIBO_decarb_SPAAC/photo-ODIBO_chrom.txt', skip=44, header=TRUE)
uv<-read.table('./data/ODIBO_decarb_SPAAC/ODIBO_UV_chrom.txt', skip=44, header=TRUE)
post<-read.table('./data/ODIBO_decarb_SPAAC/ODIBO_click_chrom.txt', skip=44, header=TRUE)

colors <- c('red', 'green3', 'purple')

quartz(width = 3.974*2, height = 1.892*2)
par(mfrow=c(3,1), yaxs='i', mar=c(4,2,0.5,1), xaxs='i')
plot(pre[,1], pre[,3], type='l', lwd=2, xlab='', ylab='', col = colors[1], ylim=c(0, 1.2*max(pre[,3])), las=1, xlim=c(0,3), axes=F)
axis(1, at=c(0,1,2,3))
mtext("LC signal", 2, 1, cex = 0.65)
abline(v = pre[which.max(pre[,3]), 1], lty=2, col = colors[1])
abline(v = uv[which.max(uv[,3]), 1], lty=2,  col = colors[2])
abline(v = post[which.max(post[,3]), 1], lty=2,  col = colors[3])
box()

plot(uv[,1], uv[,3], type='l', lwd=2, xlab='', ylab='', col = colors[2], ylim=c(0, 1.2*max(uv[,3])), las=1, xlim=c(0,3), axes=F)
axis(1, at=c(0,1,2,3))
mtext("LC signal", 2, 1, cex = 0.65)
abline(v = pre[which.max(pre[,3]), 1], lty=2, col = colors[1])
abline(v = uv[which.max(uv[,3]), 1], lty=2,  col = colors[2])
abline(v = post[which.max(post[,3]), 1], lty=2,  col = colors[3])
box()

plot(post[,1], post[,3], type='l', lwd=2, xlab='Time (min.)', ylab='', col = colors[3], ylim=c(0, 1.2*max(post[,3])), las=1, xlim=c(0,3), axes=F)
axis(1, at=c(0,1,2,3))
mtext("LC signal", 2, 1, cex = 0.65)
abline(v = pre[which.max(pre[,3]), 1], lty=2, col = colors[1])
abline(v = uv[which.max(uv[,3]), 1], lty=2,  col = colors[2])
abline(v = post[which.max(post[,3]), 1], lty=2,  col = colors[3])
box()